### ISSUE TITLE
Negative numbers?

### ISSUE THREAD

**Issue by demiro** [kimpettersen/random-sublime-text-plugin#28]
I would like to have random numbers from -10  to 10.... but if I enter -10-10 obviously doesn't work

please advise

**Comment by natharduini** [comment]
In the meantime, one "dirty" solution if you also use Emmet:
- insert random numbers from 0 to 20
- select them
- use the Emmet shortcut to decrease the numbers 10 times
Demo: http://take.ms/BkbXw

**Comment by kimpettersen** [comment]
Thanks for pointing this out @demiro and thanks for the workaround @natharduini .

This plugin desperately needs some love. In the meantime i've changed the way you separate integers by using `,` instead of `-` so you can use negative numbers

Let me know if you have any other issues and I'll look into
